apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
spec:
  refreshInterval: "30s"
  data:
    - secretKey: appname
      remoteRef:
        key: secret/data/dev/app
        property: appname
    - secretKey: db_host
      remoteRef:
        key: secret/data/dev/app
        property: db_host
    - secretKey: db_user
      remoteRef:
        key: secret/data/dev/app
        property: db_user
