apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: app-config
    creationPolicy: Owner
  data:
    - secretKey: appname
      remoteRef:
        key: secret/data/dev/app
        property: appname
    - secretKey: db_host
      remoteRef:
        key: secret/data/dev/app
        property: db_host
    - secretKey: db_user
      remoteRef:
        key: secret/data/dev/app
        property: db_user
    - secretKey: db_password
      remoteRef:
        key: secret/data/dev/app
        property: db_password

