apiVersion: batch/v1
kind: Job
metadata:
  name: python-app-migrate
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: python-app-migrate
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: migrate
          image: novadeploy/python-app:latest
          imagePullPolicy: Never
          command: ["python", "-m", "alembic", "upgrade", "head"]
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: db_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: db_host
            - name: DATABASE_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/demo
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
