apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo
spec:
  refreshInterval: "5m"
  data:
    - secretKey: appname
      remoteRef:
        key: secret/data/prod/app
        property: appname
    - secretKey: db_host
      remoteRef:
        key: secret/data/prod/app
        property: db_host
    - secretKey: db_user
      remoteRef:
        key: secret/data/prod/app
        property: db_user
