apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - env: dev
            server: https://kubernetes.default.svc
          - env: prod
            server: https://<PROD_CLUSTER_API_URL>
  template:
    metadata:
      name: "namespaces-{{env}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: git@github.com:pratapalakshmi/novadeploy.git
        targetRevision: main
        path: platform/namespaces
      destination:
        server: "{{server}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true

