apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - env: dev
            server: https://kubernetes.default.svc
          # - env: prod
          #   server: https://<PROD_CLUSTER_API_URL>
  template:
    metadata:
      name: "vault-{{env}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      sources:
        - repoURL: https://helm.releases.hashicorp.com
          chart: vault
          targetRevision: "0.27.0"
          helm:
            releaseName: vault
            valueFiles:
              - $values/platform/vault/values.yaml
        - repoURL: git@github.com:pratapalakshmi/novadeploy.git
          targetRevision: main
          ref: values
      destination:
        server: "{{server}}"
        namespace: vault
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true

