# Pulls secret/demo/app from Vault into K8s Secret app-config (refresh every 1m).
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: app-config
    creationPolicy: Owner
  data:
    - secretKey: appname
      remoteRef:
        key: secret/data/demo/app
        property: appname
    - secretKey: db_host
      remoteRef:
        key: secret/data/demo/app
        property: db_host
    - secretKey: db_user
      remoteRef:
        key: secret/data/demo/app
        property: db_user
